config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#link'
  resources :questions

  get 'link', to: 'home#link'
  get 'level1', to: 'questions#level1'
  get 'level2', to: 'questions#level2'
  get 'level3', to: 'questions#level3'

  get 'radian_frequency_method', to: 'questions#radian_frequency_method'
  get 'addition_theorem', to: 'questions#addition_theorem'
  get 'interrelationship', to: 'questions#interrelationship'
  get 'double_angle', to: 'questions#double_angle'
  get 'synthesis', to: 'questions#synthesis'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    mount_uploader :question_image, ImageUploader

    # def next
    #   Question.where("id > ?", self.id).order("id ASC").first
    # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def link
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def index
      @questions = Question.all
    end

    def new
      @question = Question.new
    end

    def create
      @question = Question.new(question_params)
        if @question.save
            redirect_to @question
        end
    end

    def show
      @question = Question.find(params[:id])
    end

    def level1
      @questions = Question.where(level: 1)
    end

    def level2
      @questions = Question.where(level: 2)
    end

    def level3
      @questions = Question.where(level: 3)
    end

    def radian_frequency_method
      @questions = Question.where(category: 1)
    end

    def addition_theorem
      @questions = Question.where(category: 2)
    end

    def interrelationship
      @questions = Question.where(category: 3)
    end

    def double_angle
      @questions = Question.where(category: 4)
    end

    def synthesis
      @questions = Question.where(category: 5)
    end

    private
          def question_params
            params.require(:question).permit(:question_image, :answer, :column, :hint, :level, :category)
          end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/link.html.erb
<div>
    <h1>レベルで選ぶ</h1>
    <ul>
        <li><%= link_to 'レベル1', level1_path %></li>
        <li><%= link_to 'レベル2', level2_path %></li>
        <li><%= link_to 'レベル3', level3_path %></li>
    </ul>
</div>

<div>
    <h1>カテゴリーで選ぶ</h1>
    <ul>
        <li><%= link_to '弧度法と度数法', radian_frequency_method_path %></li>
        <li><%= link_to '加法定理', addition_theorem_path %></li>
        <li><%= link_to '相互関係', interrelationship_path %></li>
        <li><%= link_to '二倍角の公式', double_angle_path %></li>
        <li><%= link_to '合成', synthesis_path %></li>
    </ul>
</div>

<a href="../html/home.html">問題選択画面へ</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_content.html.erb
<a href="../html/home.html">問題選択画面へ戻る</a>
<% @questions.each_with_index do |question, i| %>
    <div id = "classification<%= question.id %>">
        <p>-----<%= i + 1%>問目-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
        <p><%= image_tag(question.question_image.url, :size => "446x75") %></p>
        <p>コラム:<%= question.column %></p>
        <p>ヒント:<%= question.hint %></p>
        <p>レベル:<%= question.level %></p>

        <% case question.category %>
        <% when 1%>
        <p>カテゴリー:弧度法と度数法</p>
        <% when 2 %>
        <p>カテゴリー:加法定理</p>
        <% when 3 %>
        <p>カテゴリー:相互関係</p>
        <% when 4 %>
        <p>カテゴリー:二倍角の公式</p>
        <% when 5 %>
        <p>カテゴリー:合成</p>
        <% end %>



        <div>
            <select id="area<%= question.id %>" name="area<%= question.id %>">
              <option value="0">答えを入力してください</option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
            <p id="result<%= question.id %>"></p>
        </div>

    <button id="button<%= question.id %>">次の問題へ</button>

    </div>

    <% if i == 0 %>
        <script>
            $(function() {
                $("#classification<%= question.id %>").show();
            });
        </script>
    <% elsif @questions.length - 1 == i %>

        <script>
            $(document).ready(function(){
                $("#classification<%= question.id %>").hide();
            });

            $("#button<%= question.id %>").text("問題は以上です。正解率を確認してください（ここをクリック）");

            $("#button<%= question.id %>").on("click", function(){
                var ans = $('p.ans').length;
                var good = $('p.good').length;
                alert("あなたの正解数は" + good + "/" + ans + "(" + good/ans*100 + "%)" + "です")
            });

        </script>

    <% else %>
        <script>
            $(document).ready(function(){
                $("#classification<%= question.id %>").hide();
            });
        </script>
    <% end %>

    <script>

        $('#area<%= question.id %>').change(function() {
            var r = $('[name=area<%= question.id %>] option:selected').val();
                if (<%= question.answer %> == r) {
                    $('#result<%= question.id %>').append('<p class="ans good">大正解！！！！！</p>').css({'color':'red','font-size':'50px'});
                } else {
                    $('#result<%= question.id %>').append('<p class="ans not">不正解</p>').css({'color':'blue','font-size':'50px'});
                }
            $("#classification<%= question.id %>").next().next().next().show();
        })

    </script>

<% end %>

app/views/questions/addition_theorem.html.erb
<h1>カテゴリ別：加法定理</h1>
<%= render partial: "content" %>

app/views/questions/double_angle.html.erb
<h1>カテゴリ別：2倍角の公式</h1>
<%= render partial: "content" %>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
    <p>---------------------------------</p>
    <p>id:<%= question.id %></p>
    <%= image_tag(question.question_image.url, :size => "446x75") %>
    <p>答え（数字）:<%= question.answer %></p>
    <p>コラム:<%= question.column %></p>
    <p>ヒント:<%= question.hint %></p>
    <p>レベル:<%= question.level %></p>
    <p>カテゴリー:<%= question.category %></p>
<% end %>

app/views/questions/interrelationship.html.erb
<h1>カテゴリ別：相互関係</h1>
<%= render partial: "content" %>

app/views/questions/level1.html.erb
<h1>レベル別：レベル１</h1>
<%= render partial: "content" %>

app/views/questions/level2.html.erb
<h1>レベル別：レベル2</h1>
<%= render partial: "content" %>

app/views/questions/level3.html.erb
<h1>レベル別：レベル3</h1>
<%= render partial: "content" %>

app/views/questions/new.html.erb
<%= form_with model: @question do |form| %>
  <p>質問内容画像:<%= form.file_field :question_image %></p>
  <p>答え（数字）:<%= form.select :answer , [[1, 1], [2, 2],[3, 3], [4, 4]] %></p>
  <p>コラム:<%= form.text_field :column %></p>
  <p>ヒント:<%= form.text_field :hint %></p>
  <p>レベル:<%= form.select :level , [[1, 1], [2, 2],[3, 3]] %></p>
  <p>カテゴリー:<%= form.select :category , [["弧度法と度数法", 1], ["加法定理", 2],["相互関係", 3], ["2倍角の公式", 4], ["合成", 5]] %></p>
  <%= form.submit %>
<% end %>

<a href="../html/home.html">問題選択画面へ</a>

app/views/questions/radian_frequency_method.html.erb
<h1>カテゴリ別：弧度法と度数法</h1>
<%= render partial: "content" %>

app/views/questions/show.html.erb
<%= @question.id %><br>
<p><%= image_tag(@question.question_image.url, :size => "446x75") %></p>
<p>答え（数字）:<%= @question.answer %></p>
<p>コラム:<%= @question.column %></p>
<p>ヒント:<%= @question.hint %></p>
<p>レベル:<%= @question.level %></p>
<p>カテゴリー:<%= @question.category %></p>

<%= link_to "問題作成画面へ", new_question_path %>

app/views/questions/synthesis.html.erb
<h1>カテゴリ別：合成</h1>
<%= render partial: "content" %>